/**
 * Action Types for Admin Dashboard
 */
export const RESET_MESSAGE = 'RESET_MESSAGE';

/**
 * Admin/user action types
 */
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const CHANGE_USER_FORMDATA = 'CHANGE_USER_FORMDATA';
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE';
export const CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST';
export const CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS';
export const CONFIRM_USER_FAILURE = 'CONFIRM_USER_FAILURE';
export const RESEND_USER_CONFIRMATION_EMAIL_REQUEST = 'RESEND_USER_CONFIRMATION_EMAIL_REQUEST';
export const RESEND_USER_CONFIRMATION_EMAIL_SUCCESS = 'RESEND_USER_CONFIRMATION_EMAIL_SUCCESS';
export const RESEND_USER_CONFIRMATION_EMAIL_FAILURE = 'RESEND_USER_CONFIRMATION_EMAIL_FAILURE';
export const CHANGE_USERS_PAGE = 'CHANGE_USERS_PAGE';
export const CHANGE_USERS_LIMIT = 'CHANGE_USERS_LIMIT';
export const CHANGE_USERS_SEARCH = 'CHANGE_USERS_SEARCH';

/**
 * Admin/embeds action types
 */
export const GET_EMBEDS_REQUEST = 'GET_EMBEDS_REQUEST';
export const GET_EMBEDS_SUCCESS = 'GET_EMBEDS_SUCCESS';
export const GET_EMBEDS_FAILURE = 'GET_EMBEDS_FAILURE';
export const CHANGE_EMBEDS_PAGE = 'CHANGE_EMBEDS_PAGE';
export const CHANGE_EMBEDS_LIMIT = 'CHANGE_EMBEDS_LIMIT';
export const CHANGE_EMBEDS_SEARCH = 'CHANGE_EMBEDS_SEARCH';

/**
 * Admin/documents action types
 */
export const GET_DOCUMENTS_REQUEST = 'GET_DOCUMENTS_REQUEST';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_FAILURE = 'GET_DOCUMENTS_FAILURE';
export const CHANGE_DOCUMENTS_PAGE = 'CHANGE_DOCUMENTS_PAGE';
export const CHANGE_DOCUMENTS_LIMIT = 'CHANGE_DOCUMENTS_LIMIT';
export const CHANGE_DOCUMENTS_SEARCH = 'CHANGE_DOCUMENTS_SEARCH';

/**
 * Admin/course action types
 */
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';
export const CHANGE_COURSES_PAGE = 'CHANGE_COURSES_PAGE';
export const CHANGE_COURSES_LIMIT = 'CHANGE_COURSES_LIMIT';
export const CHANGE_COURSES_SEARCH = 'CHANGE_COURSES_SEARCH';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const CHANGE_COURSE_FORMDATA = 'CHANGE_COURSE_FORMDATA';
export const SAVE_COURSE_REQUEST = 'SAVE_COURSE_REQUEST';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAILURE = 'SAVE_COURSE_FAILURE';
export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSEFAILURE = 'DELETE_COURSE_FAILURE';

/**
 * Admin/log action types
 */
export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_FAILURE = 'GET_LOGS_FAILURE';
export const CHANGE_LOGS_PAGE = 'CHANGE_LOGS_PAGE';
export const CHANGE_LOGS_LIMIT = 'CHANGE_LOGS_LIMIT';
export const CHANGE_LOGS_SEARCH = 'CHANGE_LOGS_SEARCH';

/**
 * Admin/authattempts action types
 */
export const GET_AUTHATTEMPTS_REQUEST = 'GET_AUTHATTEMPTS_REQUEST';
export const GET_AUTHATTEMPTS_SUCCESS = 'GET_AUTHATTEMPTS_SUCCESS';
export const GET_AUTHATTEMPTS_FAILURE = 'GET_AUTHATTEMPTS_FAILURE';
export const DELETE_AUTHATTEMPTS_REQUEST = 'DELETE_AUTHATTEMPTS_REQUEST';
export const DELETE_AUTHATTEMPTS_SUCCESS = 'DELETE_AUTHATTEMPTS_SUCCESS';
export const DELETE_AUTHATTEMPTS_FAILURE = 'DELETE_AUTHATTEMPTS_FAILURE';
export const CHANGE_AUTHATTEMPTS_PAGE = 'CHANGE_AUTHATTEMPTS_PAGE';
export const CHANGE_AUTHATTEMPTS_LIMIT = 'CHANGE_AUTHATTEMPTS_LIMIT';

/**
 * Admin/recyclebin action types
 */
export const GET_RECYCLEBIN_REQUEST = 'GET_RECYCLEBIN_REQUEST';
export const GET_RECYCLEBIN_SUCCESS = 'GET_RECYCLEBIN_SUCCESS';
export const GET_RECYCLEBIN_FAILURE = 'GET_RECYCLEBIN_FAILURE';
export const CHANGE_RECYCLEBIN_PAGE = 'CHANGE_RECYCLEBIN_PAGE';
export const CHANGE_RECYCLEBIN_LIMIT = 'CHANGE_RECYCLEBIN_LIMIT';

/**
 * Admin/mail action types
 */
export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';
export const CHANGE_MAIL_DATA = 'CHANGE_MAIL_DATA';