require('scss/index');

import React from 'react';
import {render} from 'react-dom';

import Ide from '../../common/components/ide/Ide';
import SourceboxProject from '../../common/models/sourcebox';

let project = new SourceboxProject('testproject', 'c', {
  auth: window.authToken,
  server: window.server
});

// just a test, files should be generated by the server or requested via ajax
project.addFile('test.c', `
#include <stdio.h>

int main() {
#pragma message "this should appear as info"

#warning "this is a warning!!!"

    printf("What's your name? ");

    char name[256];
    fgets(name, 256, stdin);

    printf("Hello %s", name);

    return 0;
}
`.trim());

render(
  <Ide project={project}/>,
  document.getElementById('ide-container')
);
